// Package main is the entry point for neo-shadaloo.
//
//	@title			neo-shadaloo API
//	@version		1.0
//	@description	Caching proxy between the Street Fighter 6 Buckler API and PostgreSQL. Serves cached battlelog data instantly and syncs with SF6 asynchronously in the background.
//	@contact.name	Leo Alemax
//
//	@host		localhost:8080
//	@BasePath	/
//
//	@schemes	http ws
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	"github.com/joho/godotenv"
	httpswagger "github.com/swaggo/http-swagger/v2"

	"neo-shadaloo/internal/api"
	app "neo-shadaloo/internal/application/battlelog"
	appfighting "neo-shadaloo/internal/application/fighting"
	appranking "neo-shadaloo/internal/application/ranking"
	appusage "neo-shadaloo/internal/application/usage"
	_ "neo-shadaloo/docs" // generated by swag init
	"neo-shadaloo/internal/infrastructure/persistence"
	"neo-shadaloo/internal/infrastructure/realtime"
	"neo-shadaloo/internal/infrastructure/sf6"
)

func main() {
	if err := godotenv.Load(); err == nil {
		log.Println("Loaded .env file")
	}

	ctx := context.Background()

	// ── Infrastructure ───────────────────────────────────────────────────────
	if err := persistence.Connect(ctx); err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	log.Println("Connected to PostgreSQL")

	cfgRepo        := persistence.NewConfigRepository(persistence.Pool)
	battlelogRepo  := persistence.NewBattlelogRepository(persistence.Pool)
	playerIndexRepo := persistence.NewPlayerIndexRepository(persistence.Pool)
	usageRepo      := persistence.NewUsageRepository(persistence.Pool)
	fightingRepo   := persistence.NewFightingRepository(persistence.Pool)
	rankingRepo    := persistence.NewRankingRepository(persistence.Pool)
	hub            := realtime.NewHub()
	sf6Client := sf6.NewClient(cfgRepo)

	// ── Application ──────────────────────────────────────────────────────────
	svc         := app.NewBattlelogService(battlelogRepo, playerIndexRepo, sf6Client, hub)
	usageSvc    := appusage.NewUsageService(usageRepo, sf6Client)
	fightingSvc := appfighting.NewFightingService(fightingRepo, sf6Client)
	rankingSvc  := appranking.NewService(rankingRepo, sf6Client, playerIndexRepo)

	// ── API ──────────────────────────────────────────────────────────────────
	router := api.NewRouter(svc, usageSvc, fightingSvc, rankingSvc, hub)

	// Swagger UI at /docs/
	http.Handle("/docs/", httpswagger.WrapHandler)
	http.Handle("/", router)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("neo-shadaloo listening on :%s", port)
	log.Printf("Swagger UI: http://localhost:%s/docs/", port)
	if err := http.ListenAndServe(":"+port, nil); err != nil {
		log.Fatalf("Server error: %v", err)
	}
}
