// Package main is the entry point for neo-shadaloo.
//
//	@title			neo-shadaloo API
//	@version		1.0
//	@description	Caching proxy between the Street Fighter 6 Buckler API and PostgreSQL. Serves cached battlelog data instantly and syncs with SF6 asynchronously in the background.
//	@contact.name	Leo Alemax
//
//	@host		localhost:8080
//	@BasePath	/
//
//	@schemes	http ws
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/joho/godotenv"
	httpswagger "github.com/swaggo/http-swagger/v2"

	_ "neo-shadaloo/docs" // generated by swag init
	"neo-shadaloo/internal/api"
	app "neo-shadaloo/internal/application/battlelog"
	appfighting "neo-shadaloo/internal/application/fighting"
	appleague "neo-shadaloo/internal/application/league"
	appranking "neo-shadaloo/internal/application/ranking"
	appusage "neo-shadaloo/internal/application/usage"
	"neo-shadaloo/internal/infrastructure/persistence"
	"neo-shadaloo/internal/infrastructure/realtime"
	"neo-shadaloo/internal/infrastructure/sf6"
)

func main() {
	if err := godotenv.Load(); err == nil {
		log.Println("Loaded .env file")
	} else {
		log.Printf("No .env loaded: %v (using container envs)", err)
	}

	// Debug: log key envs (mascarando segredos)
	logEnv := func(k string, mask bool) {
		v := os.Getenv(k)
		if v == "" {
			log.Printf("[env] %s=<EMPTY>", k)
			return
		}
		if mask && len(v) > 10 {
			v = v[:6] + "..." + v[len(v)-4:]
		}
		log.Printf("[env] %s=%s", k, v)
	}
	logEnv("DATABASE_URL", true)
	logEnv("SF6_COOKIE", true)
	logEnv("KAFKA_BROKER", false)
	logEnv("PORT", false)

	// Loga só o host parseado do DATABASE_URL (sem credenciais)
	if cfg, err := pgxpool.ParseConfig(os.Getenv("DATABASE_URL")); err == nil {
		log.Printf("[env] DATABASE_URL host=%s port=%d db=%s user=%s",
			cfg.ConnConfig.Host, cfg.ConnConfig.Port, cfg.ConnConfig.Database, cfg.ConnConfig.User)
	} else {
		log.Printf("[env] DATABASE_URL parse error: %v", err)
	}

	ctx := context.Background()

	// ── Infrastructure ───────────────────────────────────────────────────────
	if err := persistence.Connect(ctx); err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	log.Println("Connected to PostgreSQL")

	cfgRepo := persistence.NewConfigRepository(persistence.Pool)
	battlelogRepo := persistence.NewBattlelogRepository(persistence.Pool)
	playerIndexRepo := persistence.NewPlayerIndexRepository(persistence.Pool)
	usageRepo := persistence.NewUsageRepository(persistence.Pool)
	fightingRepo := persistence.NewFightingRepository(persistence.Pool)
	rankingRepo := persistence.NewRankingRepository(persistence.Pool)
	leagueRepo := persistence.NewLeagueRepository(persistence.Pool)
	hub := realtime.NewHub()
	sf6Client := sf6.NewClient(cfgRepo)

	// ── Application ──────────────────────────────────────────────────────────
	svc := app.NewBattlelogService(battlelogRepo, playerIndexRepo, sf6Client, hub)
	usageSvc := appusage.NewUsageService(usageRepo, sf6Client)
	fightingSvc := appfighting.NewFightingService(fightingRepo, sf6Client)
	rankingSvc := appranking.NewService(rankingRepo, sf6Client, playerIndexRepo)
	leagueSvc := appleague.NewService(leagueRepo, sf6Client, playerIndexRepo)

	// ── Kafka consumers (ranking) ────────────────────────────────────────────
	if err := rankingSvc.InitKafka(ctx); err != nil {
		log.Printf("Kafka init warning (ranking sync): %v", err)
	}
	// league sync usa pool de goroutines com rate limiter (sem Kafka)

	// ── API ──────────────────────────────────────────────────────────────────
	router := api.NewRouter(svc, usageSvc, fightingSvc, rankingSvc, leagueSvc, hub)

	// Swagger UI at /docs/
	http.Handle("/docs/", httpswagger.WrapHandler)
	http.Handle("/", router)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("neo-shadaloo listening on :%s", port)
	log.Printf("Swagger UI: http://localhost:%s/docs/", port)
	if err := http.ListenAndServe(":"+port, nil); err != nil {
		log.Fatalf("Server error: %v", err)
	}
}
