// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Leo Alemax"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/battlelog/{userId}": {
            "get": {
                "description": "Returns the cached battlelog from the database. If the cache is stale (\u003e5 min), a background sync with the SF6 API is triggered without blocking the response. If no data exists yet, an empty replay list is returned and sync is triggered.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battlelog"
                ],
                "summary": "Get battlelog for a user",
                "parameters": [
                    {
                        "type": "string",
                        "example": "3378249682",
                        "description": "SF6 fighter ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/battlelog.Battlelog"
                        }
                    },
                    "400": {
                        "description": "userId required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/battlelog/{userId}/sync": {
            "post": {
                "description": "Triggers an immediate background sync with the SF6 API for the given user, regardless of cache freshness. Returns 202 immediately; the sync runs asynchronously and notifies connected WebSocket clients when complete.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battlelog"
                ],
                "summary": "Force a battlelog sync",
                "parameters": [
                    {
                        "type": "string",
                        "example": "3378249682",
                        "description": "SF6 fighter ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "sync started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "userId required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/battlelog/{userId}/ws": {
            "get": {
                "description": "Upgrades the connection to WebSocket. The server sends a JSON message ` + "`" + `{\"type\":\"update\",\"cachedAt\":\u003cms\u003e}` + "`" + ` whenever a sync completes for this user. The client should re-fetch ` + "`" + `/v1/battlelog/{userId}` + "`" + ` on receipt. A ping is sent every 30 seconds to keep the connection alive.",
                "tags": [
                    "battlelog"
                ],
                "summary": "Subscribe to real-time battlelog updates",
                "parameters": [
                    {
                        "type": "string",
                        "example": "3378249682",
                        "description": "SF6 fighter ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    },
                    "400": {
                        "description": "userId required",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/health": {
            "get": {
                "description": "Returns 200 if the server is running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "battlelog.Battlelog": {
            "type": "object",
            "properties": {
                "bannerInfo": {
                    "$ref": "#/definitions/battlelog.FighterBannerInfo"
                },
                "cachedAt": {
                    "type": "integer"
                },
                "replays": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/battlelog.Replay"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "battlelog.FavoriteCharacterLeagueInfo": {
            "type": "object",
            "properties": {
                "league_point": {
                    "type": "integer"
                },
                "league_rank": {
                    "type": "integer"
                },
                "league_rank_info": {
                    "$ref": "#/definitions/battlelog.LeagueRankInfo"
                },
                "master_league": {
                    "type": "integer"
                },
                "master_rating": {
                    "type": "integer"
                },
                "master_rating_ranking": {
                    "type": "integer"
                }
            }
        },
        "battlelog.FighterBannerInfo": {
            "type": "object",
            "properties": {
                "favorite_character_alpha": {
                    "type": "string"
                },
                "favorite_character_league_info": {
                    "$ref": "#/definitions/battlelog.FavoriteCharacterLeagueInfo"
                },
                "favorite_character_name": {
                    "type": "string"
                },
                "favorite_character_play_point": {
                    "$ref": "#/definitions/battlelog.PlayPoint"
                },
                "favorite_character_tool_name": {
                    "type": "string"
                },
                "personal_info": {
                    "$ref": "#/definitions/battlelog.PersonalInfo"
                },
                "profile_comment": {
                    "$ref": "#/definitions/battlelog.ProfileComment"
                },
                "title_data": {
                    "$ref": "#/definitions/battlelog.TitleData"
                }
            }
        },
        "battlelog.LeagueRankInfo": {
            "type": "object",
            "properties": {
                "league_rank_name": {
                    "type": "string"
                },
                "league_rank_number": {
                    "type": "integer"
                }
            }
        },
        "battlelog.PersonalInfo": {
            "type": "object",
            "properties": {
                "fighter_id": {
                    "type": "string"
                },
                "platform_name": {
                    "type": "string"
                },
                "platform_tool_name": {
                    "type": "string"
                },
                "short_id": {
                    "type": "integer"
                }
            }
        },
        "battlelog.PlayPoint": {
            "type": "object",
            "properties": {
                "battle_hub": {
                    "type": "integer"
                },
                "fighting_ground": {
                    "type": "integer"
                },
                "world_tour": {
                    "type": "integer"
                }
            }
        },
        "battlelog.PlayerInfo": {
            "type": "object",
            "properties": {
                "allow_cross_play": {
                    "type": "boolean"
                },
                "battle_input_type": {
                    "type": "integer"
                },
                "battle_input_type_name": {
                    "type": "string"
                },
                "character_id": {
                    "type": "integer"
                },
                "character_name": {
                    "type": "string"
                },
                "character_tool_name": {
                    "type": "string"
                },
                "league_point": {
                    "type": "integer"
                },
                "league_rank": {
                    "type": "integer"
                },
                "player": {
                    "$ref": "#/definitions/battlelog.PlayerRef"
                },
                "playing_character_id": {
                    "type": "integer"
                },
                "playing_character_name": {
                    "type": "string"
                },
                "playing_character_tool_name": {
                    "type": "string"
                },
                "round_results": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "battlelog.PlayerRef": {
            "type": "object",
            "properties": {
                "fighter_id": {
                    "type": "string"
                },
                "platform_id": {
                    "type": "integer"
                },
                "platform_name": {
                    "type": "string"
                },
                "platform_tool_name": {
                    "type": "string"
                },
                "short_id": {
                    "type": "integer"
                }
            }
        },
        "battlelog.ProfileComment": {
            "type": "object",
            "properties": {
                "profile_tag_name": {
                    "type": "string"
                }
            }
        },
        "battlelog.Replay": {
            "type": "object",
            "properties": {
                "player1_info": {
                    "$ref": "#/definitions/battlelog.PlayerInfo"
                },
                "player2_info": {
                    "$ref": "#/definitions/battlelog.PlayerInfo"
                },
                "replay_battle_sub_type_name": {
                    "type": "string"
                },
                "replay_battle_type": {
                    "type": "integer"
                },
                "replay_battle_type_name": {
                    "type": "string"
                },
                "replay_id": {
                    "type": "string"
                },
                "uploaded_at": {
                    "type": "integer"
                },
                "views": {
                    "type": "integer"
                }
            }
        },
        "battlelog.TitleData": {
            "type": "object",
            "properties": {
                "title_data_plate_name": {
                    "type": "string"
                },
                "title_data_val": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "ws"},
	Title:            "neo-shadaloo API",
	Description:      "Caching proxy between the Street Fighter 6 Buckler API and PostgreSQL. Serves cached battlelog data instantly and syncs with SF6 asynchronously in the background.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
