package persistence

// Country é um país do SF6 (home_id → nome + ISO 3166-1 alpha-3).
type Country struct {
	HomeID  int
	Name    string
	ISO3    string
}

// SF6 home_id mapping. Source: resposta do endpoint /ranking/league.json
// (pt-br labels) + ISO 3166-1 alpha-3 codes (mapeados manualmente).
// id 169 está ausente na resposta do SF6 (provavelmente Taiwan).
var SF6Countries = []Country{
	{1, "Afeganistão", "AFG"},
	{2, "Albânia", "ALB"},
	{3, "Algéria", "DZA"},
	{4, "Andorra", "AND"},
	{5, "Angola", "AGO"},
	{6, "Antígua e Barbuda", "ATG"},
	{7, "Argentina", "ARG"},
	{8, "Armênia", "ARM"},
	{9, "Austrália", "AUS"},
	{10, "Áustria", "AUT"},
	{11, "Azerbaijão", "AZE"},
	{12, "Bahamas", "BHS"},
	{13, "Barein", "BHR"},
	{14, "Bangladesh", "BGD"},
	{15, "Barbados", "BRB"},
	{16, "Bielorrússia", "BLR"},
	{17, "Bélgica", "BEL"},
	{18, "Belize", "BLZ"},
	{19, "Benim", "BEN"},
	{20, "Butão", "BTN"},
	{21, "Bolívia", "BOL"},
	{22, "Bósnia e Herzegovina", "BIH"},
	{23, "Botsuana", "BWA"},
	{24, "Brasil", "BRA"},
	{25, "Brunei", "BRN"},
	{26, "Bulgária", "BGR"},
	{27, "Burkina Faso", "BFA"},
	{28, "Burundi", "BDI"},
	{29, "Cabo Verde", "CPV"},
	{30, "Camboja", "KHM"},
	{31, "Camarões", "CMR"},
	{32, "Canadá", "CAN"},
	{33, "África Central", "CAF"},
	{34, "Chade", "TCD"},
	{35, "Chile", "CHL"},
	{36, "China", "CHN"},
	{37, "Colômbia", "COL"},
	{38, "Comores", "COM"},
	{39, "República do Congo", "COG"},
	{40, "Costa Rica", "CRI"},
	{41, "Costa do Marfim", "CIV"},
	{42, "Croácia", "HRV"},
	{43, "Cuba", "CUB"},
	{44, "Chipre", "CYP"},
	{45, "República Tcheca", "CZE"},
	{46, "Coreia do Norte", "PRK"},
	{47, "República Democrática do Congo", "COD"},
	{48, "Dinamarca", "DNK"},
	{49, "Djibuti", "DJI"},
	{50, "Dominica", "DMA"},
	{51, "República Dominicana", "DOM"},
	{52, "Equador", "ECU"},
	{53, "Egito", "EGY"},
	{54, "El Salvador", "SLV"},
	{55, "Guiné-Equatorial", "GNQ"},
	{56, "Eritreia", "ERI"},
	{57, "Estônia", "EST"},
	{58, "Etiópia", "ETH"},
	{59, "Fiji", "FJI"},
	{60, "Finlândia", "FIN"},
	{61, "França", "FRA"},
	{62, "Gabão", "GAB"},
	{63, "Gâmbia", "GMB"},
	{64, "Geórgia", "GEO"},
	{65, "Alemanha", "DEU"},
	{66, "Gana", "GHA"},
	{67, "Grécia", "GRC"},
	{68, "Grenada", "GRD"},
	{69, "Guatemala", "GTM"},
	{70, "Guiné", "GIN"},
	{71, "Guiné-Bissau", "GNB"},
	{72, "Guiana", "GUY"},
	{73, "Haiti", "HTI"},
	{74, "Honduras", "HND"},
	{75, "Hungria", "HUN"},
	{76, "Islândia", "ISL"},
	{77, "Índia", "IND"},
	{78, "Indonésia", "IDN"},
	{79, "Irã", "IRN"},
	{80, "Iraque", "IRQ"},
	{81, "Irlanda", "IRL"},
	{82, "Israel", "ISR"},
	{83, "Itália", "ITA"},
	{84, "Jamaica", "JAM"},
	{85, "Japão", "JPN"},
	{86, "Jordânia", "JOR"},
	{87, "Cazaquistão", "KAZ"},
	{88, "Quênia", "KEN"},
	{89, "Kiribati", "KIR"},
	{90, "Kuwait", "KWT"},
	{91, "Quirguistão", "KGZ"},
	{92, "Laos", "LAO"},
	{93, "Letônia", "LVA"},
	{94, "Líbano", "LBN"},
	{95, "Lesoto", "LSO"},
	{96, "Libéria", "LBR"},
	{97, "Líbia", "LBY"},
	{98, "Liechtenstein", "LIE"},
	{99, "Lituânia", "LTU"},
	{100, "Luxemburgo", "LUX"},
	{101, "Madagascar", "MDG"},
	{102, "Malaui", "MWI"},
	{103, "Malásia", "MYS"},
	{104, "Maldivas", "MDV"},
	{105, "Mali", "MLI"},
	{106, "Malta", "MLT"},
	{107, "Ilhas Marshall", "MHL"},
	{108, "Mauritânia", "MRT"},
	{109, "Maurício", "MUS"},
	{110, "México", "MEX"},
	{111, "Micronésia", "FSM"},
	{112, "Mônaco", "MCO"},
	{113, "Mongólia", "MNG"},
	{114, "Montenegro", "MNE"},
	{115, "Marrocos", "MAR"},
	{116, "Moçambique", "MOZ"},
	{117, "Mianmar", "MMR"},
	{118, "Namíbia", "NAM"},
	{119, "Nauru", "NRU"},
	{120, "Nepal", "NPL"},
	{121, "Países Baixos", "NLD"},
	{122, "Nova Zelândia", "NZL"},
	{123, "Nicarágua", "NIC"},
	{124, "Níger", "NER"},
	{125, "Nigéria", "NGA"},
	{126, "Noruega", "NOR"},
	{127, "Omã", "OMN"},
	{128, "Paquistão", "PAK"},
	{129, "Palau", "PLW"},
	{130, "Panamá", "PAN"},
	{131, "Papua Nova Guiné", "PNG"},
	{132, "Paraguai", "PRY"},
	{133, "Peru", "PER"},
	{134, "Filipinas", "PHL"},
	{135, "Polônia", "POL"},
	{136, "Portugal", "PRT"},
	{137, "Catar", "QAT"},
	{138, "Coreia do Sul", "KOR"},
	{139, "Moldávia", "MDA"},
	{140, "Romênia", "ROU"},
	{141, "Rússia", "RUS"},
	{142, "Ruanda", "RWA"},
	{143, "São Cristóvão e Névis", "KNA"},
	{144, "Santa Lúcia", "LCA"},
	{145, "São Vicente e Granadinas", "VCT"},
	{146, "Samoa", "WSM"},
	{147, "San Marino", "SMR"},
	{148, "São Tomé e Príncipe", "STP"},
	{149, "Arábia Saudita", "SAU"},
	{150, "Senegal", "SEN"},
	{151, "Sérvia", "SRB"},
	{152, "Seicheles", "SYC"},
	{153, "Serra Leoa", "SLE"},
	{154, "Cingapura", "SGP"},
	{155, "Eslováquia", "SVK"},
	{156, "Eslovênia", "SVN"},
	{157, "Ilhas Salomão", "SLB"},
	{158, "Somália", "SOM"},
	{159, "África do Sul", "ZAF"},
	{160, "Sudão do Sul", "SSD"},
	{161, "Espanha", "ESP"},
	{162, "Sri Lanka", "LKA"},
	{163, "Sudão", "SDN"},
	{164, "Suriname", "SUR"},
	{165, "Suazilândia", "SWZ"},
	{166, "Suécia", "SWE"},
	{167, "Suíça", "CHE"},
	{168, "Síria", "SYR"},
	// id 169 ausente (provavelmente Taiwan, excluído pelo SF6)
	{170, "Tajiquistão", "TJK"},
	{171, "Tailândia", "THA"},
	{172, "Macedônia", "MKD"},
	{173, "Timor-Leste", "TLS"},
	{174, "Togo", "TGO"},
	{175, "Tonga", "TON"},
	{176, "Trinidad e Tobago", "TTO"},
	{177, "Tunísia", "TUN"},
	{178, "Turquia", "TUR"},
	{179, "Turcomenistão", "TKM"},
	{180, "Tuvalu", "TUV"},
	{181, "Uganda", "UGA"},
	{182, "Ucrânia", "UKR"},
	{183, "Emirados Árabes Unidos", "ARE"},
	{184, "Reino Unido", "GBR"},
	{185, "Tanzânia", "TZA"},
	{186, "Estados Unidos", "USA"},
	{187, "Uruguai", "URY"},
	{188, "Uzbequistão", "UZB"},
	{189, "Vanuatu", "VUT"},
	{190, "Venezuela", "VEN"},
	{191, "Vietnã", "VNM"},
	{192, "Iêmen", "YEM"},
	{193, "Zâmbia", "ZMB"},
	{194, "Zimbábue", "ZWE"},
}
